services:
  web:
    image: ${IMAGE}
    ports:
      - "8000:8000"
    environment:
      # Required by settings.py
      SECRET_KEY_DJANGO: ${SECRET_KEY_DJANGO?SECRET_KEY_DJANGO is required}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
    restart: unless-stopped
